FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build   
WORKDIR /PostalCode
   
# copy source
COPY postal.code/. .

RUN dotnet restore  
RUN dotnet build --configuration Release 
RUN dotnet publish -c Release -o out   

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime   
WORKDIR /PostalCode   
COPY --from=build /PostalCode/out ./

# Padrão de container ASP.NET
# ENTRYPOINT ["dotnet", "postal.code.api.dll"]
# Opção utilizada pelo Heroku
# CMD ASPNETCORE_URLS=http://*:$PORT dotnet postal.code.api.dll

CMD ASPNETCORE_URLS=http://*:$PORT dotnet postal.code.api.dll